# Generated by Django 4.2.6 on 2023-10-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(max_length=200, null=True, upload_to='store/images'),
        ),
    ]
